repos:
  -   repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.2.1
      hooks:
        - id: ruff
          args: [ --fix, --exit-non-zero-on-fix ]
        - id: ruff-format
          args: [ --line-length=100 ]
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
      - id: check-json
      - id: check-ast
      - id: check-yaml
        args: ['--unsafe']
      - id: detect-private-key
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.982
      hooks:
      - id: mypy
        args: [--follow-imports=silent, --ignore-missing-imports, --exclude="src/yessql/__init__.py"]
        exclude: "tests/.+"
  - repo: local
    hooks:
      - id: tests
        name: run tests
        entry: make test-cov
        language: python
        pass_filenames: false
        stages:
          - commit